### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by petroclus** [timskillman/Pi3C#1]
I cloned the repository, upgraded the solution to VS2019, changed platform to x86 and tried to build the invaders project but got a compile error (cannot find mystrtof).

Error	LNK2019	unresolved external symbol "double __cdecl Pi3CfastRead::mystrtof(char const *)" (?mystrtof@Pi3CfastRead@@YANPBD@Z) referenced in function "class vec2f __cdecl Pi3CfileOBJ::readVec2f(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?readVec2f@Pi3CfileOBJ@@YA?AVvec2f@@AAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)

**Comment by jamieS95** [comment]
same issues

**Comment by timskillman** [comment]
Thanks Petroclus -  I'll take a look

**Comment by timskillman** [comment]
Fixed issue.  Also fixed slowdown to create trees and allow alien ships to navigate landscape;  this was due to removing the creation of a colliderGrid when loading OBJ files.  colliderGrid can now be specified in OBJ loading if required.
